### ISSUE TITLE
 Nonexistent function 'initialise' in base 'JNISingleton'

### ISSUE THREAD

**Issue by KeysonRaphael** [azatgt1996/UnityAdsGodotAndroid#1]
i followed the steps on the page but got this error when running on android:

 **Nonexistent function 'initialise' in base 'JNISingleton'**

code:

```
var unity_ad

func _ready():
	# Check if plugin was added to the project
	if Engine.has_singleton("UnityAdsGodotAndroid"):
	  unity_ad = Engine.get_singleton("UnityAdsGodotAndroid")
	  unity_ad.initialise("1234567", true) # error line
```
**godot version: 3.2.3.stable**

**Comment by azatgt1996** [comment]
> Hi! Do you have the opportunity to check on the version 3.4.3+. 
I checked the plugin on the v3.4.3 and it's OK.

**Comment by KeysonRaphael** [comment]
i tried with the version you specified and now i got this error:

```
2022-07-02 10:01:30.996 7584-7758/org.godotengine.infinite I/UnityAds: com.unity3d.services.core.api.Sdk.logInfo() (line:85) :: Requesting configuration from https://publisher-config.unityads.unity3d.com/games/1234567/configuration?deviceMake=Google&screenDensity=320&screenSize=268435794&idfi=8fb85fbd-2c90-4f48-b1a1-40f388e612ab&advertisingTrackingId=00000000-0000-0000-0000-000000000000&limitAdTracking=false&installationId=8fb85fbd-2c90-4f48-b1a1-40f388e612ab&connectionType=wifi&screenHeight=720&screenWidth=1184&bundleId=org.godotengine.infinite&encrypted=false&rooted=false&platform=android&sdkVersion=4210&osVersion=11&deviceModel=sdk_gphone_x86_arm&language=en_US&test=true&first=true&userLevelFlagDetected=false
2022-07-02 10:01:31.429 7584-7758/org.godotengine.infinite E/UnityAds: com.unity3d.services.core.api.Sdk.logError() (line:73) :: Game Configuration Request Failed: {"message":"FAILED_WITH_ERROR_RESPONSE","nativeRequest":{"method":0,"url":"https://publisher-config.unityads.unity3d.com/games/1234567/configuration?deviceMake=Google&screenDensity=320&screenSize=268435794&idfi=8fb85fbd-2c90-4f48-b1a1-40f388e612ab&advertisingTrackingId=00000000-0000-0000-0000-000000000000&limitAdTracking=false&installationId=8fb85fbd-2c90-4f48-b1a1-40f388e612ab&connectionType=wifi&screenHeight=720&screenWidth=1184&bundleId=org.godotengine.infinite&encrypted=false&rooted=false&platform=android&sdkVersion=4210&osVersion=11&deviceModel=sdk_gphone_x86_arm&language=en_US&test=true&first=true&userLevelFlagDetected=false","headers":[],"retryCount":0,"options":{"retries":2,"retryDelay":10000,"followRedirects":false,"retryWithConnectionEvents":true}},"nativeResponse":{"url":"https://publisher-config.unityads.unity3d.com/games/1234567/configuration?deviceMake=Google&screenDensity=320&screenSize=268435794&idfi=8fb85fbd-2c90-4f48-b1a1-40f388e612ab&advertisingTrackingId=00000000-0000-0000-0000-000000000000&limitAdTracking=false&installationId=8fb85fbd-2c90-4f48-b1a1-40f388e612ab&connectionType=wifi&screenHeight=720&screenWidth=1184&bundleId=org.godotengine.infinite&encrypted=false&rooted=false&platform=android&sdkVersion=4210&osVersion=11&deviceModel=sdk_gphone_x86_arm&language=en_US&test=true&first=true&userLevelFlagDetected=false","response":"{\"error\":\"request conflicts with the configuration - mismatched platform\"}\n","responseCode":409,"headers":[["Transfer-Encoding","chunked"],["Alt-Svc","h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000"],["Access-Control-Allow-Origin","*"],["X-Android-Received-Millis","1656766891404"],["Date","Sat, 02 Jul 2022 13:01:34 GMT"],["X-Origlength","75"],["Via","1.1 google"],["X-Android-Selected-Protocol","http/1.1"],["X-Service","ads-sdk-configuration"],["X-Android-Response-Source","NETWORK 409"],["Vary","Accept-Encoding"],["X-Android-Sent-Millis","1656766891225"],["Content-Type","application/json"]]}}
2022-07-02 10:01:31.460 7584-7647/org.godotengine.infinite E/UnityAds: com.unity3d.services.core.configuration.InitializeThread$InitializeStateCreate.execute() (line:503) :: Unity Ads SDK fail to initialize due to configuration error
2022-07-02 10:01:31.462 7584-7758/org.godotengine.infinite E/UnityAds: com.unity3d.services.core.api.Sdk.logError() (line:73) :: Initialization error: Unity Ads SDK fail to initialize due to configuration error
2022-07-02 10:01:31.467 7584-7647/org.godotengine.infinite E/UnityAds: com.unity3d.services.core.configuration.InitializeThread$InitializeStateError.execute() (line:542) :: Unity Ads init: halting init in create webapp: Unity Ads SDK fail to initialize due to configuration error
2022-07-02 10:01:31.478 7584-7647/org.godotengine.infinite E/UnityAds: com.unity3d.services.core.configuration.InitializationNotificationCenter.triggerOnSdkInitializationFailed() (line:62) :: SDK Failed to Initialize due to Unity Ads SDK fail to initialize due to configuration error
2022-07-02 10:01:31.480 7584-7584/org.godotengine.infinite W/GodotPlugin: Invalid arguments count. Should be 0  but is 1
2022-07-02 10:01:31.481 7584-7584/org.godotengine.infinite W/GodotPlugin: Invalid arguments count. Should be 0  but is 1
2022-07-02 10:01:31.481 7584-7584/org.godotengine.infinite D/AndroidRuntime: Shutting down VM
    
    
    --------- beginning of crash
2022-07-02 10:01:31.482 7584-7584/org.godotengine.infinite E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.godotengine.infinite, PID: 7584
    java.lang.IllegalArgumentException: Invalid arguments count. Should be 0  but is 1
        at org.godotengine.godot.plugin.GodotPlugin.emitSignal(GodotPlugin.java:368)
        at org.godotengine.godot.plugin.GodotPlugin.emitSignal(GodotPlugin.java:343)
        at com.azatgt.unityadsgodotandroid.UnityAdsGodotAndroid.onInitializationFailed(UnityAdsGodotAndroid.java:110)
        at com.unity3d.services.core.properties.SdkProperties.notifyInitializationFailed(SdkProperties.java:56)
        at com.unity3d.services.core.configuration.CoreModuleConfiguration$1.run(CoreModuleConfiguration.java:85)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
2022-07-02 10:01:31.828 7584-7584/org.godotengine.infinite I/Process: Sending signal. PID: 7584 SIG: 9
```

code:
```
var unity_ad

func _ready():
	# Check if plugin was added to the project
	if Engine.has_singleton("UnityAdsGodotAndroid"):
	  unity_ad = Engine.get_singleton("UnityAdsGodotAndroid")
	  unity_ad.initialise("1234567", true) # project id and TestMode enabled
	  unity_ad.connect("onUnityBannerFailedToLoad", self, "_on_banner_failed_to_load")
	  
	  unity_ad.connect("onUnityInterstitialAdsLoaded", self, "_on_interstitial_loaded")
	  unity_ad.connect("onUnityInterstitialAdsFailedToLoad", self, "_on_interstitial_failed_to_load")
	  unity_ad.connect("onUnityInterstitialAdsShowComplete", self, "_on_interstitial_closed")
	  
	  unity_ad.connect("onUnityRewardedAdsLoaded", self, "_on_rewarded_loaded")
	  unity_ad.connect("onUnityRewardedAdsFailedToLoad", self, "_on_rewarded_failed_to_load")
	  unity_ad.connect("onUnityRewardedAdsShowComplete", self, "_on_rewarded")
```

**godot version: v3.4.3.stable**

**Comment by azatgt1996** [comment]
Hi! Is the problem still actual? If yes, please send a minimal project so that I can check. I will try help:)

**Comment by azatgt1996** [comment]
Could you find out exactly where the error occurs? (using break points)

**Comment by KeysonRaphael** [comment]
I will try again this week, and return here, thank's for the answer anyway! :+1:
